Implemented a variant with a status icon
soberhacker/obsidian-telegram-sync pull request #192
Opened 2023-08-13 13:15 UTC by efokin

Error logging have not been removed yet

2023-08-15 20:12 UTC, soberhacker requested changes

2023-08-16 20:52 UTC, efokin commented on src/main.ts
> +	statusIcon: HTMLElement | null;
Переиспользовал :?

2023-08-16 20:52 UTC, efokin commented on src/main.ts
> +		if(this.unloadingPlugin) return;
Done

2023-08-16 20:52 UTC, efokin commented on src/main.ts
> +	botStateSetToConnected(): void {
упростил

2023-08-16 20:54 UTC, efokin commented on src/settings/Settings.ts
> +	hideConnectedStatusBar() {
лучше сделать опрос
иногда пользователи хотят видет состояние OK

2023-08-16 21:16 UTC, efokin commented on src/main.ts
> +		this.unloadingPlugin = true;
Нужен статус, что плагин в процессе выгрузки.
Без этого статуса с момент отключения бота будет появляться ошибка, но разрыв соединения при выгрузке плагина - это ожидаемое поведение.

2023-08-16 21:17 UTC, efokin commented on src/telegram/user/user.ts
> -		plugin.userConnected = await client.isAuthorizedAsUser();
Вернул

2023-08-16 21:17 UTC, efokin commented on src/telegram/user/user.ts
> -		plugin.userConnected = false;
Вернул

2023-08-16 21:17 UTC, efokin commented on src/telegram/user/user.ts
> -		plugin.userConnected = false;
Вернул

2023-08-16 21:17 UTC, efokin commented on src/telegram/user/user.ts
> -		plugin.userConnected = await client.isAuthorizedAsUser();
Вернул

2023-08-16 21:18 UTC, efokin commented on src/main.ts
> +		this.botConnected = false;
Упростил

2023-08-17 09:05 UTC, soberhacker requested changes

2023-08-17 09:05 UTC, soberhacker commented on src/main.ts
> +	private botConnected: "connected" | "disconnected" = "disconnected";
тогда переменную botState нужно назвать :))

2023-08-17 19:20 UTC, efokin commented on src/main.ts
> +	private botConnected: "connected" | "disconnected" = "disconnected";
done

2023-08-20 15:51 UTC, soberhacker requested changes

2023-08-20 15:51 UTC, soberhacker commented on src/telegram/bot/bot.ts
> +		plugin.botStateSetTo("connected");
getters и setters по классике начинаются с get и set соответственно
setBotState() - и короче выглядит

2023-08-20 15:51 UTC, soberhacker commented on src/main.ts
> +	botIsConnected(): boolean {
булеан функции по классике начинаются с is, т.е. isBotConnected() будет более правильно

2023-08-20 15:51 UTC, soberhacker commented on src/settings/Settings.ts
> +	needToLogBotError(): boolean;
тут этой функции не место, этот класс потом сохраняется в JSON настройки, зачем там быть этой функции не понятно. Это чисто для хранения интерфейс. ПРавильное место: TelegramSyncSettingTab

2023-08-20 15:51 UTC, soberhacker commented on src/settings/Settings.ts
> +								`Parameter How to inform about bot staus has unknown type of value ${value}`,
staus

2023-08-20 15:51 UTC, soberhacker commented on src/settings/Settings.ts
> +					"show-bot-logs": "show only messages about bot status change",
"hide, log errors"
"show all states"
"show only error"

2023-08-20 17:55 UTC, efokin commented on src/main.ts
> +				!this.botState &&
В чем вопрос?
Diff получился в результате просьбы по переименованию.
Могу предложить замену на botIsConnected()

2023-08-20 18:02 UTC, efokin commented on src/main.ts
> +			case HowToInformAboutBotStatus.showBotLogs:
В современных IDE переименование - это просто.
Хочешь botStatus получаешь botStatus.

2023-08-20 18:48 UTC, efokin commented on src/main.ts
> +	updatePluginStatusIcon(): void {
оставил одну функции
разница в том, что в одном случае нужне ресет, а в другом нет.

2023-08-20 18:52 UTC, efokin commented on src/main.ts
> +		if (this.statusIcon !== undefined && this.connectedStatusBarShouldBeHidden()) {
Не уверен, что это одно и тоже.
this.statusIcon - это про состояние ресурса иконки. Статус бар алоцирован или нет.
А this.connectedStatusBarShouldBeHidden() - это свойства соединения и конфигурации.

2023-08-20 18:54 UTC, efokin commented on src/telegram/bot/bot.ts
> +		plugin.botStateSetTo("connected");
Done

2023-08-20 18:58 UTC, efokin commented on src/settings/Settings.ts
> +	needToLogBotError(): boolean;
Здесь в одном параметре на самом деле три параметра.
Одни про логирование, другой про два конфигурационных состояния иконки.
Как это перенесит в TelegramSyncSettingTab пока не понял.

2023-08-20 19:08 UTC, efokin commented on src/settings/Settings.ts
> +					"show-bot-logs": "show only messages about bot status change",
Имеешь ввиду переименование
"show-bot-logs" -> "show only error"
"show-bot-status-bar" -> "show all states"
"show-bot-status-bar-errors-only" - > "show only error state"
?

Здесь три категории:
- последовательность параметров
- коротконое название
- полное название

2023-08-20 19:11 UTC, efokin commented on src/main.ts
> +	botIsConnected(): boolean {
Done

2023-08-20 19:12 UTC, efokin commented on src/settings/Settings.ts
> +								`Parameter How to inform about bot staus has unknown type of value ${value}`,
Done

2023-08-20 19:16 UTC, efokin commented on src/main.ts
> +		// Bot is disconnected
Done

2023-08-20 19:18 UTC, efokin commented on src/main.ts
> +	private connectedStatusBarShouldBeHidden() {
Done

2023-08-20 19:19 UTC, efokin commented on src/settings/Settings.ts
> +export const ParameterNameHowToInformAboutBotStatus = "Bot connection staus";
Плагин поставил

2023-08-20 19:22 UTC, efokin commented on src/settings/Settings.ts
> +export const ParameterNameHowToInformAboutBotStatus = "Bot connection staus";
Done

2023-08-20 19:24 UTC, efokin commented on src/settings/Settings.ts
> +export enum HowToInformAboutBotStatus {
Done

2023-08-20 19:27 UTC, efokin commented on src/settings/Settings.ts
> +			.setDesc("Please choose how do what to be informed about bot connection status")
done

2023-08-20 19:30 UTC, efokin commented on src/settings/Settings.ts
> +	showBotLogs = "show-bot-logs",
Надо подумать.
Такой вариант подойдет?

2023-08-20 22:30 UTC, soberhacker approved these changes

2023-08-20 22:31 UTC, soberhacker commented
feat: add connection status indicator

2023-08-20 22:31 UTC, soberhacker commented
feat: add connection status indicator

2023-08-20 22:32 UTC, merged